### PR TITLE
Add two Snack deployments and two Emoji deployments

### PR DESCRIPTION
**Pull request by nicks**
Hello @dbentley, @jazzdan,

Please review the following commits I made in branch nicks/moresnacks:

677e7d841f15b426ef3ef95c1d2b1f1a7e47a044 (2018-11-09 17:52:58 -0500)
Add two Snack pods and two Emoji pods

### CODE REVIEW

**Comment by nicks** [comment]
everything *mostly* works OK out of the box. Did we get additional info on what part of this flow isn't working out of the box? There are definitely bugs but nothing preventing me from using it, so not sure what we consider blocking.

**Comment by nicks** [comment]
awww scratch that, i found issues!

**Comment by jazzdan** [comment]
@nicks should this be merged or closed?

**Comment by nicks** [comment]
i wanted to merge one of the other outstanding changes that helps with double deployments

**Pull request closed without merging**
